//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        public int Id_post { get; set; }
        public Nullable<int> Topic_id { get; set; }
        public Nullable<int> User_id { get; set; }
        [Required(ErrorMessage = "Put the data in the field")]
        [Display(Name = "User name")]
        public string User_name { get; set; }
        [Required(ErrorMessage = "Put the data in the field")]
        [Display(Name = "Text")]
        public string Post_text { get; set; }
        public Nullable<System.DateTime> Post_date { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual Users Users { get; set; }
    }
}
